language: node_js
node_js:
- '8'
- '9'
script: yarn test
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    tags: true
    repo: lifeomic/eslint-plugin-node
    node: '8'
